# Generated by Django 2.2.2 on 2019-06-12 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_auto_20190612_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomments',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
