# Generated by Django 2.2.2 on 2019-06-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_auto_20190612_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dates.EventComments'),
        ),
    ]
