# Generated by Django 2.2.2 on 2019-06-15 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0005_auto_20190612_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomments',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
