# Generated by Django 2.2.2 on 2019-07-07 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shredmap', '0004_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shredmap.Location'),
        ),
        migrations.AlterField(
            model_name='locationcomments',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shredmap.Location'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shredmap.Location'),
        ),
        migrations.AlterField(
            model_name='tricks',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tricks', to='shredmap.Location'),
        ),
        migrations.CreateModel(
            name='SkateObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skateobjects', to='shredmap.Location')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_object_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
